<a href="https://colab.research.google.com/github/sidharth-ds/TASK-1-to-7/blob/main/Numpy_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
np.__version__

'1.21.5'

In [ ]:
np.show_config()

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
x = np.zeros(10)
x.size

10

In [ ]:
x = np.zeros(10)
x.itemsize

8

In [ ]:
x.size * x.itemsize  # total size

80

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info(np.add)

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
x = np.zeros(10)
x[4]=1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
x = np.arange(10,50)
x[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
x = np.arange(9)
x.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
np.eye(3,3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
x = np.random.random((3,3,3))      # 3-rows, 3-columns, 3-times
x

array([[[0.38948847, 0.62193196, 0.16538686],
        [0.48942005, 0.1622609 , 0.96750271],
        [0.10143077, 0.89027633, 0.94978172]],

       [[0.960888  , 0.18065582, 0.39074558],
        [0.25502442, 0.13258636, 0.36343318],
        [0.5675189 , 0.19703302, 0.38908351]],

       [[0.90491001, 0.20722495, 0.59034041],
        [0.52489149, 0.7283299 , 0.29709467],
        [0.11161152, 0.53040736, 0.97103884]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
x = np.random.random((10,10))    # 10-rows, 10-columns
x.min(),x.max()

(0.001561132785821484, 0.9903808132116186)

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
x = np.random.random(30)    
x.mean()

0.5357156303611315

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
x = np.ones((5,5),dtype='int')
x[1:-1,1:-1] = 0                #  1st & last row, 1st & last column : assigned 0
x

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
x = np.random.randint(10,size=(5,5))   # values upto 10
x

array([[0, 8, 9, 8, 6],
       [9, 4, 0, 8, 8],
       [2, 2, 0, 9, 6],
       [7, 2, 8, 1, 7],
       [5, 4, 0, 0, 9]])

In [ ]:
padding = np.pad(x,pad_width=1)
padding

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 8, 9, 8, 6, 0],
       [0, 9, 4, 0, 8, 8, 0],
       [0, 2, 2, 0, 9, 6, 0],
       [0, 7, 2, 8, 1, 7, 0],
       [0, 5, 4, 0, 0, 9, 0],
       [0, 0, 0, 0, 0, 0, 0]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan

nan

In [ ]:
np.nan == np.nan

False

In [ ]:
np.inf > np.nan

False

In [ ]:
np.nan - np.nan

nan

In [ ]:
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
x = np.diag(np.arange(1,5))
x

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [ ]:
x = np.diag(np.arange(1,5), k=-1)  #  k<0 means diagonal below main diagonal
x

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
x = np.ones((8,8),dtype='int')
x[::2,::2]=0
x[1::2,1::2]=0
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
x = np.unravel_index(100,(6,7,8))        # Converts an array of flat indices into a tuple of coordinate arrays.
x                                  # coordinates of 100th element in tuple is given

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
arr = np.array([[0,1], [1,0]])     # 1st row is [0,1], 2nd row is [1,0]
x = np.tile(arr,(4,4))         # it is repeated 4 times row-wise, 4-times column-wise
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
X = np.random.randint(25,size=(5,5))
X

array([[24, 19, 12, 24,  2],
       [12,  6,  1, 18, 18],
       [20,  4, 15,  1,  5],
       [13, 22,  6, 18, 13],
       [24, 12,  7,  4, 18]])

In [ ]:
Xmax, Xmin = X.max(), X.min()
X = (X-Xmin) / (Xmax-Xmin)         # normalization formula
X

array([[1.        , 0.7826087 , 0.47826087, 1.        , 0.04347826],
       [0.47826087, 0.2173913 , 0.        , 0.73913043, 0.73913043],
       [0.82608696, 0.13043478, 0.60869565, 0.        , 0.17391304],
       [0.52173913, 0.91304348, 0.2173913 , 0.73913043, 0.52173913],
       [1.        , 0.47826087, 0.26086957, 0.13043478, 0.73913043]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
custom_dtype = np.dtype([              # ubyte : unsigned byte
                  ("r", np.ubyte),
                  ("g", np.ubyte),
                  ("b", np.ubyte),
                  ("a", np.ubyte)  ])
custom_dtype

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
print(np.ones((5,3)))
print(np.ones((3,2)))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [ ]:
x = np.dot(np.ones((5,3)), np.ones((3,2)))
x

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
x[(3<x) & (x<8)] = x[(3<x) & (x<8)] * -1
x

array([ 0,  1,  2,  3, -4, -5, -6, -7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

* axis : None or int or tuple of ints, optional Axis or axes along which a sum is performed.  The default, axis=None, will sum all of the elements of the input array.  
* If axis is negative: it counts from the last to the first axis.

In [ ]:
sum(range(5),-1) 

9

In [ ]:
from numpy import *
sum(range(5),-1)

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = 3

In [ ]:
Z**Z     # ** means power

27

* Bitwise operators act on bits and perform the bit-by-bit operations. These are used to operate on binary numbers.

In [ ]:
2 << Z >> 2        # <<	means Bitwise left shift    # >> means	Bitwise right shift

4

In [ ]:
Z <- Z         # Z < (Z-Z)

False

In [ ]:
1j * Z

3j

In [ ]:
Z/1/1

3.0

In [ ]:
Z<Z>Z

False

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0)

array(0)

In [ ]:
np.array(0) / np.array(0)       # / means Division (float): divides the first operand by the second

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


nan

In [ ]:
np.array(0) // np.array(0)     #  // means Division (floor): divides the first operand by the second

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


0

In [ ]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
x = np.random.uniform(-10,+10,10)
x

array([-8.28166842, -3.5424148 ,  5.70729455,  2.22922725,  4.98372811,
        4.22934837,  0.93878817, -6.91666044, -8.20891643,  8.62828197])

* copysign - Change the sign of x1 to that of x2, element-wise
* ceil - roundoff to upper limit
* abs - Calculates the absolute value element-wise.

In [ ]:
np.copysign(np.ceil(np.abs(x)) , x)

array([-9., -4.,  6.,  3.,  5.,  5.,  1., -7., -9.,  9.])

#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
x1 = np.random.randint(0,6,10)
x2 = np.random.randint(0,8,10)

np.intersect1d(x1,x2)

array([0, 1, 4, 5])

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
old_settings = np.seterr(all='ignore')   # Set error handling to known state
x = np.ones(1)/0
np.seterr(**old_settings)  # reset to default

{'divide': 'ignore', 'invalid': 'ignore', 'over': 'ignore', 'under': 'ignore'}

In [ ]:
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.emath.sqrt(-1), np.sqrt(-1) 

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


(1j, nan)

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
yesterday = np.datetime64('today') - np.timedelta64(1)
yesterday

numpy.datetime64('2022-02-19')

In [ ]:
today     = np.datetime64('today')
today

numpy.datetime64('2022-02-20')

In [ ]:
tomorrow  = np.datetime64('today') + np.timedelta64(1)
tomorrow

numpy.datetime64('2022-02-21')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
x = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')    # D means Days   # start,end,step
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
x = np.ones(5)*2
y = np.ones(5)*3
print(x)
print(y)

[2. 2. 2. 2. 2.]
[3. 3. 3. 3. 3.]


In [ ]:
np.add(x,y,out=y)    # (A+B)     # out : A location into which the result is stored.

array([5., 5., 5., 5., 5.])

In [ ]:
np.divide(x,2,out=x)      # (A/2)

array([1., 1., 1., 1., 1.])

In [ ]:
np.negative(x,out=x)      # (-A/2)

array([-1., -1., -1., -1., -1.])

In [ ]:
np.multiply(x,y)      # (A+B)*(-A/2)

array([-5., -5., -5., -5., -5.])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
x = np.random.uniform(0,10,10)
x

array([9.93353016, 1.98008508, 2.41597217, 9.36881345, 1.50581195,
       1.04461302, 5.2761145 , 8.70782046, 4.59785076, 4.93615752])

In [ ]:
x - x % 2 

array([8., 0., 2., 8., 0., 0., 4., 8., 4., 4.])

In [ ]:
np.floor(x)

array([9., 1., 2., 9., 1., 1., 5., 8., 4., 4.])

In [ ]:
np.ceil(x)

array([10.,  2.,  3., 10.,  2.,  2.,  6.,  9.,  5.,  5.])

In [ ]:
x.astype(int)

array([9, 1, 2, 9, 1, 1, 5, 8, 4, 4])

In [ ]:
np.trunc(x)        #  nearest integer  which is closer to zero

array([9., 1., 2., 9., 1., 1., 5., 8., 4., 4.])

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
x = np.zeros((5,5))
x

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
x = x + np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

numpy.fromiter(iter, dtype, count= -1)
  * iter = iterable object
  * count = The number of items to read from iterable. The default is -1, which means all data is read.

In [ ]:
def generate():
    for i in range(10):
        yield i
x = np.fromiter(generate(),dtype=int,count=-1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

linspace - Returns evenly spaced numbers over a specified interval.
  * linspace(start, stop, num=10, endpoint=True)
  * num : Number of samples to generate
  * endpoint : If True, stop is the last sample. Otherwise, it is not included.

In [ ]:
x = np.linspace(0,1,10,endpoint=False)          
x

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
x = np.random.randint(10,size=10)
x

array([6, 9, 1, 7, 9, 7, 6, 7, 4, 5])

In [ ]:
x.sort()
x

array([1, 4, 5, 6, 6, 7, 7, 7, 9, 9])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
x = np.arange(6)
np.add.reduce(x)

15

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
A = np.random.randint(0,5,10)
B = np.random.randint(0,5,10)
print(A)
print(B)

[4 4 4 4 4 4 4 2 0 4]
[2 4 4 0 3 2 2 0 2 0]


In [ ]:
check_equal = np.allclose(A,B)     # Returns True if two arrays are element-wise equal within a tolerance.
check_equal

False

In [ ]:
check_equal = np.array_equal(A,B)   # True if two arrays have the same shape and elements
check_equal

False

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
x = np.ones(10)
x.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

* Cartesian coordinate : using x-axis, y-axis.
* Polar coordinate : a pair of coordinates locating the position of a point in a plane, 
  - the first being the length of the straight line ( r ) connecting the point to the origin, 
  - and the second the angle ( θ ) made by this line with a fixed line.

In [ ]:
x = np.random.random((10,2))
x

array([[0.20492079, 0.7891533 ],
       [0.93309791, 0.71960324],
       [0.79911179, 0.68285422],
       [0.68779228, 0.35094585],
       [0.01189728, 0.0092015 ],
       [0.24110357, 0.0800646 ],
       [0.97247585, 0.39980227],
       [0.14260059, 0.11403646],
       [0.3125595 , 0.5578828 ],
       [0.62462942, 0.92212365]])

In [ ]:
X,Y = x[:,0], x[:,1]     # creating cartesian coordinate

In [ ]:
R = np.sqrt(X**2+Y**2)          
T = np.arctan2(Y,X)       #  To convert from Cartesian coordinates to polar coordinates

T

array([1.31673579, 0.65693037, 0.7071103 , 0.47181376, 0.65831699,
       0.32061812, 0.39005392, 0.67455274, 1.06010998, 0.97541247])

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
x = np.random.randint(10,size=10)
x

array([5, 0, 9, 4, 6, 4, 6, 6, 2, 5])

In [ ]:
x[x.argmax()] = 0        # the argmax function returns the "index" of the maximum value of a Numpy array.
x

array([5, 0, 0, 4, 6, 4, 6, 6, 2, 5])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

* meshgrid is a function that creates a rectangular grid out of 2 given 1-dimensional arrays that denotes the Matrix or Cartesian indexing

In [ ]:
Z = np.zeros((3,3), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,3), np.linspace(0,1,3))
print(Z)

[[(0. , 0. ) (0.5, 0. ) (1. , 0. )]
 [(0. , 0.5) (0.5, 0.5) (1. , 0.5)]
 [(0. , 1. ) (0.5, 1. ) (1. , 1. )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
X = np.arange(8)
Y = X + 0.5

C = 1.0 / np.subtract.outer(X, Y)     # Cauchy matrix
print(np.linalg.det(C))           # Compute the determinant of an array. # The determinant of a 2-D array [[a, b], [c, d]] is ad - bc

3638.163637117973


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
#  scalar data structure is the most basic data type that holds only a single atomic value at a time.

for dtype in [np.int8, np.int32, np.int64]:
   print('min :',np.iinfo(dtype).min)
   print('max :',np.iinfo(dtype).max)

min : -128
max : 127
min : -2147483648
max : 2147483647
min : -9223372036854775808
max : 9223372036854775807


In [ ]:
for dtype in [np.float32, np.float64]:
   print('min :',np.finfo(dtype).min)
   print('max :',np.finfo(dtype).max)
   print('eps :',np.finfo(dtype).eps)   # eps : The difference between 1.0 and the next smallest representable float larger than 1.0

min : -3.4028235e+38
max : 3.4028235e+38
eps : 1.1920929e-07
min : -1.7976931348623157e+308
max : 1.7976931348623157e+308
eps : 2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(threshold=float("inf"))   # These options determine the way floating point numbers, arrays and other NumPy objects are displayed.
x = np.zeros((5,24))
print(x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
# A scalar data structure is the most basic data type that holds only a single atomic value at a time.
# A vector is a tuple of one or more values called scalars.

x = np.arange(15)  # vector
y = np.random.uniform(10,20)   # scalar
print(x)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
13.47350032477436


In [ ]:
index = (np.abs(x-y)).argmin()    # index value of the closest
x[index]                      # closest value 

13

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
x = np.ones(6, [ ('position',[ ('x', float, 1),
                               ('y', float, 1)  ]),
                   ('color', [ ('r', float, 1),
                               ('g', float, 1),
                               ('b', float, 1)  ])  
                   ])
print(x)

[((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))
 ((1., 1.), (1., 1., 1.)) ((1., 1.), (1., 1., 1.))]


/usr/local/lib/python3.7/dist-packages/numpy/core/numeric.py:204: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  a = empty(shape, dtype, order)


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])  # coordinates

D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)   # point by point distances
print(D)

[[0.         0.16206876 0.72379621 0.40368223 0.49892604 0.44419083
  0.81042852 0.29123553 0.40796066 0.63789201]
 [0.16206876 0.         0.74351409 0.24467812 0.33734262 0.29110981
  0.82702817 0.4211357  0.53135584 0.51864533]
 [0.72379621 0.74351409 0.         0.88393732 0.85736838 0.74684088
  0.08684231 0.55237336 0.50162968 0.6146934 ]
 [0.40368223 0.24467812 0.88393732 0.         0.13534957 0.18088946
  0.95941557 0.66042906 0.76587748 0.46119176]
 [0.49892604 0.33734262 0.85736838 0.13534957 0.         0.11067891
  0.92580522 0.72400793 0.81959159 0.3561337 ]
 [0.44419083 0.29110981 0.74684088 0.18088946 0.11067891 0.
  0.81586975 0.63906758 0.72800525 0.28109157]
 [0.81042852 0.82702817 0.08684231 0.95941557 0.92580522 0.81586975
  0.         0.63583433 0.57926109 0.66187061]
 [0.29123553 0.4211357  0.55237336 0.66042906 0.72400793 0.63906758
  0.63583433 0.         0.1172895  0.73348204]
 [0.40796066 0.53135584 0.50162968 0.76587748 0.81959159 0.72800525
  0.57926109 0.11728

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
X = (np.random.rand(15)*100).astype(np.float32)  # float (32 bits) array
X

array([84.55781 , 14.387435, 98.30659 , 95.516945, 40.376774, 52.318745,
       73.16803 , 25.962032, 98.27026 , 74.448845, 25.91712 , 86.851845,
       57.002438, 20.511923, 91.86871 ], dtype=float32)

In [ ]:
Y = X.view(np.int32)    # New view of array with the same data.
print(Y)

[84 14 98 95 40 52 73 25 98 74 25 86 57 20 91]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
             ''')
Z = np.genfromtxt(s, delimiter=",", dtype= np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  import sys


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
x = np.arange(9).reshape(3,3)
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
for index, value in np.ndenumerate(x):  # Multidimensional index iterator  # both index & values
    print(index, value)

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


In [ ]:
x.shape

(3, 3)

In [ ]:
for index in np.ndindex(x.shape):   # An N-dimensional iterator object to index arrays  # only index
    print(index, x[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,5), np.linspace(-1,1,5))   # coordinates

D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
Gaussian = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )   # formula

print(Gaussian)

[[0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.60653066 0.8824969  1.         0.8824969  0.60653066]
 [0.53526143 0.77880078 0.8824969  0.77880078 0.53526143]
 [0.36787944 0.53526143 0.60653066 0.53526143 0.36787944]]


#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n = 5
p = 8    # p elements 

x = np.zeros((n,n))   # 2-d array

np.put(x, np.random.choice(range(n*n), p),5)

print(x)

[[5. 0. 0. 5. 0.]
 [0. 0. 0. 0. 0.]
 [0. 5. 5. 5. 5.]
 [0. 0. 0. 5. 0.]
 [0. 0. 0. 0. 5.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
x = np.random.rand(3, 5)      # 3-rows, 5-cols

ans = x - x.mean(axis=1, keepdims=True)         # axis=1 means across the columns for each row
ans

array([[ 0.23443069,  0.6271141 , -0.26013247, -0.33782012, -0.26359219],
       [-0.21771965,  0.02214929, -0.10563096,  0.38798679, -0.08678547],
       [ 0.16122629,  0.1825722 , -0.26583112, -0.19516562,  0.11719825]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
x = np.random.randint(0,26,(5,5))
x

array([[13, 10, 23, 14,  9],
       [ 3,  5,  1,  6, 25],
       [20, 15, 14,  9,  0],
       [21,  3,  8, 22,  6],
       [ 2,  2, 16, 18,  5]])

In [ ]:
n = 2
x[ x[:,n].argsort() ]

array([[ 3,  5,  1,  6, 25],
       [21,  3,  8, 22,  6],
       [20, 15, 14,  9,  0],
       [ 2,  2, 16, 18,  5],
       [13, 10, 23, 14,  9]])

#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
x = np.random.randint(0,2,(4,10))
x

array([[1, 0, 0, 0, 1, 1, 0, 1, 0, 1],
       [0, 0, 0, 0, 1, 1, 1, 1, 0, 0],
       [1, 1, 1, 0, 0, 1, 0, 1, 0, 1],
       [1, 0, 0, 0, 1, 1, 1, 1, 1, 0]])

In [ ]:
(~x.any(axis=0)).any()   # axis=0 means across the rows for each column

True

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
x = np.random.uniform(1,2,10)
z = 0.8
x

array([1.91714033, 1.1160197 , 1.92430542, 1.54849848, 1.67648823,
       1.97049841, 1.39575565, 1.66362616, 1.49659803, 1.13861547])

In [ ]:
x.flat[np.abs(x-z).argmin()]       # flat : 1-D iterator over the array.

0.7213515688285658

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
print(A)
print(B)

[[0]
 [1]
 [2]]
[[0 1 2]]


In [ ]:
iterator = np.nditer([A,B,None])

for x,y,z in iterator: 
    z = x + y

print(iterator.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
Z = np.ones(10)    # vector
I = np.random.randint(0,10,5)     # second vector
print(Z)
print(I)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[6 3 6 2 6]


In [ ]:
Z = Z + np.bincount(I, minlength=len(Z))     # bincount : Count number of occurrences of each value in array of non-negative ints.
print(Z)

np.add.at(Z, I, 1)
print(Z)

[1. 1. 2. 2. 1. 1. 4. 1. 1. 1.]
[1. 1. 3. 3. 1. 1. 7. 1. 1. 1.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
X = [1,2,3,4,5,6,7,8,9]   # weights
I = [1,1,2,3,5,8,5,3,4]      # index list   # there are no 0,6,7. hence 0

F = np.bincount(I,X)
print(F)

[ 0.  3.  3. 12.  9. 12.  0.  0.  6.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
I

array([[[3, 2, 0],
        [3, 3, 3],
        [3, 3, 0],
        ...,
        [1, 1, 2],
        [1, 1, 1],
        [3, 2, 0]],

       [[3, 0, 3],
        [3, 3, 1],
        [1, 0, 3],
        ...,
        [3, 2, 1],
        [1, 1, 1],
        [1, 3, 1]],

       [[1, 0, 0],
        [1, 1, 3],
        [0, 3, 1],
        ...,
        [2, 1, 3],
        [2, 0, 3],
        [0, 1, 1]],

       ...,

       [[0, 2, 1],
        [3, 0, 2],
        [2, 0, 2],
        ...,
        [0, 1, 3],
        [3, 1, 3],
        [0, 1, 1]],

       [[0, 0, 1],
        [0, 1, 2],
        [1, 3, 2],
        ...,
        [0, 0, 1],
        [0, 3, 1],
        [1, 1, 2]],

       [[2, 0, 0],
        [3, 2, 0],
        [3, 3, 3],
        ...,
        [1, 2, 1],
        [0, 2, 3],
        [3, 0, 1]]], dtype=uint8)

* reshape(rows,columns)

In [ ]:
colors = np.unique(I.reshape(-1, 3), axis=0)  # -1 :  simply means that it is an unknown dimension and we want numpy to figure it out
print(colors)

[[0 0 0]
 [0 0 1]
 [0 0 2]
 [0 0 3]
 [0 1 0]
 [0 1 1]
 [0 1 2]
 [0 1 3]
 [0 2 0]
 [0 2 1]
 [0 2 2]
 [0 2 3]
 [0 3 0]
 [0 3 1]
 [0 3 2]
 [0 3 3]
 [1 0 0]
 [1 0 1]
 [1 0 2]
 [1 0 3]
 [1 1 0]
 [1 1 1]
 [1 1 2]
 [1 1 3]
 [1 2 0]
 [1 2 1]
 [1 2 2]
 [1 2 3]
 [1 3 0]
 [1 3 1]
 [1 3 2]
 [1 3 3]
 [2 0 0]
 [2 0 1]
 [2 0 2]
 [2 0 3]
 [2 1 0]
 [2 1 1]
 [2 1 2]
 [2 1 3]
 [2 2 0]
 [2 2 1]
 [2 2 2]
 [2 2 3]
 [2 3 0]
 [2 3 1]
 [2 3 2]
 [2 3 3]
 [3 0 0]
 [3 0 1]
 [3 0 2]
 [3 0 3]
 [3 1 0]
 [3 1 1]
 [3 1 2]
 [3 1 3]
 [3 2 0]
 [3 2 1]
 [3 2 2]
 [3 2 3]
 [3 3 0]
 [3 3 1]
 [3 3 2]
 [3 3 3]]


In [ ]:
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
A = np.random.uniform(0,1,(3,3))
B = np.random.uniform(0,1,(3,3))

print(A)
print(B)

[[0.32962909 0.81439868 0.85670072]
 [0.79464595 0.0676864  0.3708671 ]
 [0.55171605 0.1466836  0.10697775]]
[[0.35805794 0.65040612 0.36693067]
 [0.36239429 0.11664927 0.9691935 ]
 [0.30832877 0.13983575 0.67777697]]


In [ ]:
np.diag(np.dot(A, B))    #  product of two arrays. 

array([0.67730523, 0.57659864, 0.41711338])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
x = np.ones((5,5,3))      # 5-times 5x3
y = 2*np.ones((5,5))

print(x)
print(y)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [ ]:
print(x * y[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
x = np.arange(25).reshape(5,5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
x[[0,1]] = x[[1,0]]         # swapping rows based on index
x

array([[ 5,  6,  7,  8,  9],
       [ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
x[:,[0,1]] = x[:,[1,0]]         # swapping columns based on index
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
x = np.random.randint(0,5,10)
x

array([0, 3, 0, 0, 1, 4, 2, 2, 4, 2])

In [ ]:
np.logical_not(x, out=x)      # negating a boolean

array([1, 0, 1, 1, 0, 0, 0, 0, 0, 0])

In [ ]:
x = np.random.uniform(-1.0,1.0,10)
x

array([-0.59310561, -0.82549215,  0.65199228,  0.52662003,  0.6866143 ,
        0.74018708,  0.88936678, -0.56498095,  0.04629021,  0.75743312])

In [ ]:
np.negative(x, out=x)      # change the sign of a float inplace

array([ 0.59310561,  0.82549215, -0.65199228, -0.52662003, -0.6866143 ,
       -0.74018708, -0.88936678,  0.56498095, -0.04629021, -0.75743312])

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.arange(1, 15)
print(np.lib.stride_tricks.sliding_window_view(Z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

* The rank of the matrix refers to the number of linearly independent rows or columns in the matrix. 
* The rank of the matrix is the dimension of the vector space obtained by its columns. 
* A matrix is said to be of rank zero when all of its elements become zero. 
* The rank of a matrix cannot exceed more than the number of its rows or columns. The rank of the null matrix is zero.

In [ ]:
Z = np.random.randint(10,size=(5,5))
Z

array([[5, 9, 5, 7, 3],
       [9, 5, 6, 7, 0],
       [1, 8, 4, 4, 9],
       [3, 0, 2, 7, 8],
       [7, 4, 0, 4, 4]])

In [ ]:
rank = np.linalg.matrix_rank(Z)
print(rank)

5


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
x = np.random.randint(5,15,100)
x

array([14,  8, 14,  7,  6,  6,  8,  9, 14, 11, 13,  9, 10,  7, 14,  7,  7,
       12, 10, 14, 14, 14,  7,  8,  9, 13,  8, 13, 13,  6,  5, 14, 11, 11,
        7,  5,  5, 11,  6,  8,  6, 12, 13, 12,  9,  8, 14, 10, 14, 14,  9,
       14, 12,  6,  7, 12, 13, 12, 12, 12, 13, 10,  6,  7,  7, 11,  7, 13,
       12, 14,  7,  6, 10,  8,  7, 12,  6,  8, 13,  6,  7, 13,  7, 12,  6,
       13, 11, 14,  6,  9,  6, 10, 12, 13, 13, 13, 12,  9,  5, 14])

In [ ]:
np.bincount(x)

array([ 0,  0,  0,  0,  0,  4, 13, 14,  8,  7,  6,  6, 13, 14, 15])

In [ ]:
np.bincount(x).argmax()

14

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
x = np.random.randint(0,5,(10,10))
print(np.lib.stride_tricks.sliding_window_view(x, window_shape=(3, 3)))

[[[[2 1 4]
   [1 0 4]
   [4 2 3]]

  [[1 4 2]
   [0 4 3]
   [2 3 3]]

  [[4 2 4]
   [4 3 0]
   [3 3 1]]

  [[2 4 2]
   [3 0 2]
   [3 1 2]]

  [[4 2 4]
   [0 2 4]
   [1 2 2]]

  [[2 4 0]
   [2 4 4]
   [2 2 0]]

  [[4 0 4]
   [4 4 3]
   [2 0 3]]

  [[0 4 3]
   [4 3 3]
   [0 3 4]]]


 [[[1 0 4]
   [4 2 3]
   [0 0 0]]

  [[0 4 3]
   [2 3 3]
   [0 0 4]]

  [[4 3 0]
   [3 3 1]
   [0 4 3]]

  [[3 0 2]
   [3 1 2]
   [4 3 3]]

  [[0 2 4]
   [1 2 2]
   [3 3 2]]

  [[2 4 4]
   [2 2 0]
   [3 2 1]]

  [[4 4 3]
   [2 0 3]
   [2 1 3]]

  [[4 3 3]
   [0 3 4]
   [1 3 3]]]


 [[[4 2 3]
   [0 0 0]
   [2 3 2]]

  [[2 3 3]
   [0 0 4]
   [3 2 1]]

  [[3 3 1]
   [0 4 3]
   [2 1 4]]

  [[3 1 2]
   [4 3 3]
   [1 4 3]]

  [[1 2 2]
   [3 3 2]
   [4 3 2]]

  [[2 2 0]
   [3 2 1]
   [3 2 2]]

  [[2 0 3]
   [2 1 3]
   [2 2 2]]

  [[0 3 4]
   [1 3 3]
   [2 2 1]]]


 [[[0 0 0]
   [2 3 2]
   [4 3 0]]

  [[0 0 4]
   [3 2 1]
   [3 0 0]]

  [[0 4 3]
   [2 1 4]
   [0 0 1]]

  [[4 3 3]
   [1 4 3]
   [0 1 4]]

  [[3 3 2]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p, n = 2, 3

x = np.ones((p,n,n))      #  set of p matrices wich shape (n,n)
y = np.ones((p,n,1))      #  set of p vectors with shape (n,1)

print(x)
print(y)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[[1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]]]


* axes = 0 : tensor product 
* axes = 1 : tensor dot product 
* axes = 2 : (default) tensor double contraction 


In [ ]:
ans = np.tensordot(x, y, axes=[[0, 2], [0, 1]])
print(ans)

[[6.]
 [6.]
 [6.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
n = 5
x = np.random.randint(1,100,100)
x

array([18, 28, 94, 24, 82, 82, 63,  7, 71,  7, 22, 71, 17, 61, 90, 19, 63,
       21,  4, 14, 87, 66, 37, 50, 58, 54,  4,  9, 34, 62,  6, 73,  7, 77,
       74, 18, 60, 89, 65, 90, 84,  3, 50, 22, 67, 86, 99, 11, 58, 25, 26,
       43, 66, 20, 31, 66, 60, 66, 38, 85, 75, 72, 50, 35, 96, 78, 71, 57,
       54, 47, 51, 52, 51, 46, 85, 76, 92, 10, 57, 37, 31, 61, 47, 39, 86,
       51, 51, 69, 54, 93, 40, 60, 72, 34, 43, 58, 71, 93, 28, 82])

In [ ]:
x[np.argsort(x)[-n:]]

array([93, 93, 94, 96, 99])

In [ ]:
x[np.argpartition(-x,n)[:n]]

array([93, 96, 94, 99, 93])

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)